#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=reminderjoblist@gmail.com
#spring.mail.password=@utom4t1c
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#mail.smtp.debug=true
#server.servlet.context-path=/api
#server.port = 8088

spring.mail.host=smtp.gmail.com
spring.mail.port= 465
spring.mail.username=seanalessandro.sal@gmail.com
spring.mail.password=iyotmsmsdeoigzxz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.test-connection=true
server.servlet.context-path=/api
server.port = ${port:8090}